### ISSUE TITLE
Not very notable yet

### ISSUE THREAD

**Issue by rdebath** [samsartor/JFlick#1]
I've tried to add your interpreter to my [Speed tests](http://esolangs.org/wiki/User:Rdebath#Performance_Testing) but it prints out a '~' character before reading input, this means most of the tests fail and it looks really bad.

BTW: Just so you know, I HATE JAVA. So I'd need a *.jar file to test 'cause the compiler never works.

PS: Thanks for the release file!

**Comment by rdebath** [comment]
Nevermind, I was able to work around with your '-i' option.

**Comment by samsartor** [comment]
I am glad that worked, in the future I might make "-s" default.
